services:
  app:
    image: gradle:jdk21
    container_name: app
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./server:/srv:cached
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /srv
    depends_on:
      - db
    command:
      /bin/bash -c "./gradlew flywayRepair && ./gradlew build && java -jar ./build/libs/demo-0.0.1-SNAPSHOT.jar"

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "dev"
    ports:
      - "5432:5432"
    volumes:
      - dbvol:/var/lib/postgresql/data
      - ./forDocker/db/initdb:/docker-entrypoint-initdb.d

volumes:
  dbvol:
  